export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const UPDATE_CART_ITEMS = "UPDATE_CART_ITEMS";
export const REMOVE_CART_ITEMS = "REMOVE_CART_ITEMS";
export const REMOVE_ALL_CART_ITEMS = "REMOVE_ALL_CART_ITEMS";